import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import NavBar from "@/components/NavBar";
import Providers from "@/components/Providers";
import { SiteFooter } from "@/components/Footer";
import ClerkProviderWithTheme from "@/components/ClerkProviderWithTheme";
const inter = Inter({ subsets: ["latin"] });
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Event Management platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(inter.className, "min-h-full")}
        suppressHydrationWarning
      >
        <ClerkProviderWithTheme>
          <Providers>
            <NavBar />
            <main className="min-h-[100vh]">{children}</main>
            <SiteFooter />
          </Providers>
        </ClerkProviderWithTheme>
      </body>
    </html>
  );
}
