export enum EventStatus {
  NOT_CONFIRMED,
  UPCOMING,
  STARTED,
  ENDED,
}

export enum EventType {
  CONFERENCE,
  SEMINARS_WORKSHOPS,
  SPORTS,
  WEDDINGS_CELEBRATION,
  FASHION,
  CONCERTS,
  MEETINGS,
  FESTIVALS,
  TRADE_SHOWS_EXPOS,
  FUNDRAISERS_CHARITY,
  NETWORKING,
  PRODUCT_LAUNCHES,
  CORPORATE_RETREATS,
}
