name: CI Pipeline

on: [push]

jobs:
  test:
    name: Type Check, Lint, Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install Dependencies
        run: npm i --legacy-peer-deps

      # - name: Run TypeScript Type Check
      #   run: npx tsc --noEmit

      # - name: Run ESLint
      #   run: npm run lint

      - name: Build Next.js App
        run: npm run build

      - name: Run Jest Tests
        run: npm test
